name: Deploy to FTP (production)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: "deploy-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  ftp-deploy:
    name: Upload site over FTPS
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:       ${{ secrets.FTP_SERVER }}
          protocol:     ftps
          username:     ${{ secrets.FTP_USERNAME }}
          password:     ${{ secrets.FTP_PASSWORD }}
          server-dir:   ${{ secrets.FTP_DIR }}
          # local-dir: ./dist/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .ftp-deploy-sync-state.json
